/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAvatar: typeof import('./src/components/AppAvatar.vue')['default']
    AppAvatarLink: typeof import('./src/components/AppAvatarLink.vue')['default']
    AppError: typeof import('./src/components/AppError.vue')['default']
    AppErrorDev: typeof import('./src/components/AppErrorDev.vue')['default']
    AppErrorProd: typeof import('./src/components/AppErrorProd.vue')['default']
    AppInputLiveEditText: typeof import('./src/components/AppInputLiveEditText.vue')['default']
    AppLoader: typeof import('./src/components/AppLoader.vue')['default']
    AuthLayout: typeof import('./src/components/layout/AuthLayout.vue')['default']
    Avatar: typeof import('./src/components/ui/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./src/components/ui/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./src/components/ui/avatar/AvatarImage.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    GuestLayout: typeof import('./src/components/layout/GuestLayout.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    NavBarTop: typeof import('./src/components/layout/NavBarTop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
    SideBarLinks: typeof import('./src/components/layout/SideBarLinks.vue')['default']
  }
}
